# import subprocess
# import json

import commands
import do

blockchain = 'cmpe'
stream_name = 'stream5'
user_key = {}

# this will be generated by chaitras code
data = {'username':'miro', 'wallet':'14td6', 'email':'miro@miro.com'}
data1 = {'balance' : 65}

# commands.liststreams(blockchain)
# commands.createstream(blockchain, stream_name)
# commands.subscribe(blockchain, stream_name)
# commands.liststreamitems(blockchain, stream_name)
# commands.publish(blockchain, stream_name, "key1", data1)

# do.add_new_user(blockchain, stream_name, user_key, data)

